name: Run Sauna News Scraper Daily

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch repo contents

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests ollama supabase datetime dateutil

      - name: Run Sauna News Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python scrape_news.py
